-- =============================================================================
-- seed.sql — Reference data
-- =============================================================================
-- This is PRODUCTION data, not demo content: the administrative divisions of
-- Uzbekistan, voice classifications and the festival's age categories. It is
-- idempotent (ON CONFLICT on the natural `code` key), so re-running it after a
-- schema change refreshes names without duplicating rows.
--
-- Demo/editorial content lives in `seed_demo.sql` and is optional.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Regions — 12 viloyats + Karakalpakstan + Tashkent city
-- -----------------------------------------------------------------------------
insert into public.regions (code, name_uz, name_ru, name_en, sort_order) values
  ('tashkent-city', 'Toshkent shahri',           'город Ташкент',            'Tashkent City',    1),
  ('tashkent',      'Toshkent viloyati',         'Ташкентская область',      'Tashkent Region',  2),
  ('andijan',       'Andijon viloyati',          'Андижанская область',      'Andijan Region',   3),
  ('bukhara',       'Buxoro viloyati',           'Бухарская область',        'Bukhara Region',   4),
  ('fergana',       'Farg''ona viloyati',        'Ферганская область',       'Fergana Region',   5),
  ('jizzakh',       'Jizzax viloyati',           'Джизакская область',       'Jizzakh Region',   6),
  ('namangan',      'Namangan viloyati',         'Наманганская область',     'Namangan Region',  7),
  ('navoiy',        'Navoiy viloyati',           'Навоийская область',       'Navoiy Region',    8),
  ('kashkadarya',   'Qashqadaryo viloyati',      'Кашкадарьинская область',  'Kashkadarya Region', 9),
  ('samarkand',     'Samarqand viloyati',        'Самаркандская область',    'Samarkand Region', 10),
  ('sirdaryo',      'Sirdaryo viloyati',         'Сырдарьинская область',    'Sirdaryo Region',  11),
  ('surkhandarya',  'Surxondaryo viloyati',      'Сурхандарьинская область', 'Surkhandarya Region', 12),
  ('khorezm',       'Xorazm viloyati',           'Хорезмская область',       'Khorezm Region',   13),
  ('karakalpakstan','Qoraqalpog''iston Respublikasi', 'Республика Каракалпакстан', 'Republic of Karakalpakstan', 14)
on conflict (code) do update
  set name_uz = excluded.name_uz,
      name_ru = excluded.name_ru,
      name_en = excluded.name_en,
      sort_order = excluded.sort_order;

-- -----------------------------------------------------------------------------
-- Districts
-- -----------------------------------------------------------------------------
-- Joined to their region by natural code so the insert never depends on a UUID
-- generated by a previous run.
with data (region_code, code, name_uz, name_ru, name_en) as (values
  -- Tashkent city ------------------------------------------------------------
  ('tashkent-city', 'tc-bektemir',     'Bektemir',        'Бектемирский',      'Bektemir'),
  ('tashkent-city', 'tc-chilanzar',    'Chilonzor',       'Чиланзарский',      'Chilanzar'),
  ('tashkent-city', 'tc-mirobod',      'Mirobod',         'Мирабадский',       'Mirobod'),
  ('tashkent-city', 'tc-ulugbek',      'Mirzo Ulug''bek', 'Мирзо-Улугбекский', 'Mirzo Ulugbek'),
  ('tashkent-city', 'tc-olmazor',      'Olmazor',         'Алмазарский',       'Olmazor'),
  ('tashkent-city', 'tc-sergeli',      'Sergeli',         'Сергелийский',      'Sergeli'),
  ('tashkent-city', 'tc-shayxontohur', 'Shayxontohur',    'Шайхантахурский',   'Shaykhantakhur'),
  ('tashkent-city', 'tc-uchtepa',      'Uchtepa',         'Учтепинский',       'Uchtepa'),
  ('tashkent-city', 'tc-yakkasaroy',   'Yakkasaroy',      'Яккасарайский',     'Yakkasaroy'),
  ('tashkent-city', 'tc-yashnobod',    'Yashnobod',       'Яшнабадский',       'Yashnobod'),
  ('tashkent-city', 'tc-yunusobod',    'Yunusobod',       'Юнусабадский',      'Yunusobod'),
  ('tashkent-city', 'tc-yangihayot',   'Yangihayot',      'Янгихаётский',      'Yangihayot'),
  -- Tashkent region ----------------------------------------------------------
  ('tashkent', 'tr-bekobod',       'Bekobod',        'Бекабадский',       'Bekobod'),
  ('tashkent', 'tr-boka',          'Bo''ka',         'Букинский',         'Boka'),
  ('tashkent', 'tr-bostonliq',     'Bo''stonliq',    'Бостанлыкский',     'Bostonliq'),
  ('tashkent', 'tr-chinoz',        'Chinoz',         'Чиназский',         'Chinoz'),
  ('tashkent', 'tr-ohangaron',     'Ohangaron',      'Ахангаранский',     'Ohangaron'),
  ('tashkent', 'tr-oqqorgon',      'Oqqo''rg''on',   'Аккурганский',      'Oqqorgon'),
  ('tashkent', 'tr-parkent',       'Parkent',        'Паркентский',       'Parkent'),
  ('tashkent', 'tr-piskent',       'Piskent',        'Пскентский',        'Piskent'),
  ('tashkent', 'tr-qibray',        'Qibray',         'Кибрайский',        'Qibray'),
  ('tashkent', 'tr-quyichirchiq',  'Quyi Chirchiq',  'Нижнечирчикский',   'Quyi Chirchiq'),
  ('tashkent', 'tr-ortachirchiq',  'O''rta Chirchiq','Среднечирчикский',  'Orta Chirchiq'),
  ('tashkent', 'tr-yangiyol',      'Yangiyo''l',     'Янгиюльский',       'Yangiyol'),
  ('tashkent', 'tr-yuqorichirchiq','Yuqori Chirchiq','Верхнечирчикский',  'Yuqori Chirchiq'),
  ('tashkent', 'tr-zangiota',      'Zangiota',       'Зангиатинский',     'Zangiota'),
  ('tashkent', 'tr-nurafshon',     'Nurafshon shahri','город Нурафшан',   'Nurafshon City'),
  ('tashkent', 'tr-angren',        'Angren shahri',  'город Ангрен',      'Angren City'),
  ('tashkent', 'tr-chirchiq',      'Chirchiq shahri','город Чирчик',      'Chirchiq City'),
  ('tashkent', 'tr-olmaliq',       'Olmaliq shahri', 'город Алмалык',     'Olmaliq City'),
  -- Andijan ------------------------------------------------------------------
  ('andijan', 'an-andijon',    'Andijon tumani', 'Андижанский',    'Andijan District'),
  ('andijan', 'an-asaka',      'Asaka',          'Асакинский',     'Asaka'),
  ('andijan', 'an-baliqchi',   'Baliqchi',       'Балыкчинский',   'Baliqchi'),
  ('andijan', 'an-boz',        'Bo''z',          'Бузский',        'Boz'),
  ('andijan', 'an-buloqboshi', 'Buloqboshi',     'Булакбашинский', 'Buloqboshi'),
  ('andijan', 'an-izboskan',   'Izboskan',       'Избасканский',   'Izboskan'),
  ('andijan', 'an-jalaquduq',  'Jalaquduq',      'Джалакудукский', 'Jalaquduq'),
  ('andijan', 'an-marhamat',   'Marhamat',       'Мархаматский',   'Marhamat'),
  ('andijan', 'an-oltinkol',   'Oltinko''l',     'Алтынкульский',  'Oltinkol'),
  ('andijan', 'an-paxtaobod',  'Paxtaobod',      'Пахтаабадский',  'Paxtaobod'),
  ('andijan', 'an-qorgontepa', 'Qo''rg''ontepa', 'Кургантепинский','Qorgontepa'),
  ('andijan', 'an-shahrixon',  'Shahrixon',      'Шахриханский',   'Shahrixon'),
  ('andijan', 'an-ulugnor',    'Ulug''nor',      'Улугнорский',    'Ulugnor'),
  ('andijan', 'an-xojaobod',   'Xo''jaobod',     'Ходжаабадский',  'Xojaobod'),
  ('andijan', 'an-andijon-c',  'Andijon shahri', 'город Андижан',  'Andijan City'),
  ('andijan', 'an-xonobod-c',  'Xonobod shahri', 'город Ханабад',  'Xonobod City'),
  -- Bukhara ------------------------------------------------------------------
  ('bukhara', 'bu-buxoro',       'Buxoro tumani',  'Бухарский',      'Bukhara District'),
  ('bukhara', 'bu-gijduvon',     'G''ijduvon',     'Гиждуванский',   'Gijduvon'),
  ('bukhara', 'bu-jondor',       'Jondor',         'Жондорский',     'Jondor'),
  ('bukhara', 'bu-kogon',        'Kogon tumani',   'Каганский',      'Kogon District'),
  ('bukhara', 'bu-olot',         'Olot',           'Алатский',       'Olot'),
  ('bukhara', 'bu-peshku',       'Peshku',         'Пешкунский',     'Peshku'),
  ('bukhara', 'bu-qorakol',      'Qorako''l',      'Каракульский',   'Qorakol'),
  ('bukhara', 'bu-qorovulbozor', 'Qorovulbozor',   'Караулбазарский','Qorovulbozor'),
  ('bukhara', 'bu-romitan',      'Romitan',        'Ромитанский',    'Romitan'),
  ('bukhara', 'bu-shofirkon',    'Shofirkon',      'Шафирканский',   'Shofirkon'),
  ('bukhara', 'bu-vobkent',      'Vobkent',        'Вабкентский',    'Vobkent'),
  ('bukhara', 'bu-buxoro-c',     'Buxoro shahri',  'город Бухара',   'Bukhara City'),
  ('bukhara', 'bu-kogon-c',      'Kogon shahri',   'город Каган',    'Kogon City'),
  -- Fergana ------------------------------------------------------------------
  ('fergana', 'fa-beshariq',   'Beshariq',       'Бешарыкский',    'Beshariq'),
  ('fergana', 'fa-bogdod',     'Bog''dod',       'Багдадский',     'Bogdod'),
  ('fergana', 'fa-buvayda',    'Buvayda',        'Бувайдинский',   'Buvayda'),
  ('fergana', 'fa-dangara',    'Dang''ara',      'Дангаринский',   'Dangara'),
  ('fergana', 'fa-fargona',    'Farg''ona tumani','Ферганский',    'Fergana District'),
  ('fergana', 'fa-furqat',     'Furqat',         'Фуркатский',     'Furqat'),
  ('fergana', 'fa-oltiariq',   'Oltiariq',       'Алтыарыкский',   'Oltiariq'),
  ('fergana', 'fa-qoshtepa',   'Qo''shtepa',     'Куштепинский',   'Qoshtepa'),
  ('fergana', 'fa-rishton',    'Rishton',        'Риштанский',     'Rishton'),
  ('fergana', 'fa-sox',        'So''x',          'Сохский',        'Sox'),
  ('fergana', 'fa-toshloq',    'Toshloq',        'Ташлакский',     'Toshloq'),
  ('fergana', 'fa-uchkoprik',  'Uchko''prik',    'Учкуприкский',   'Uchkoprik'),
  ('fergana', 'fa-yozyovon',   'Yozyovon',       'Язъяванский',    'Yozyovon'),
  ('fergana', 'fa-fargona-c',  'Farg''ona shahri','город Фергана', 'Fergana City'),
  ('fergana', 'fa-margilon',   'Marg''ilon shahri','город Маргилан','Margilan City'),
  ('fergana', 'fa-qoqon',      'Qo''qon shahri', 'город Коканд',   'Kokand City'),
  ('fergana', 'fa-quvasoy',    'Quvasoy shahri', 'город Кувасай',  'Quvasoy City'),
  -- Jizzakh ------------------------------------------------------------------
  ('jizzakh', 'ji-arnasoy',    'Arnasoy',          'Арнасайский',    'Arnasoy'),
  ('jizzakh', 'ji-baxmal',     'Baxmal',           'Бахмальский',    'Baxmal'),
  ('jizzakh', 'ji-dostlik',    'Do''stlik',        'Дустликский',    'Dostlik'),
  ('jizzakh', 'ji-forish',     'Forish',           'Фаришский',      'Forish'),
  ('jizzakh', 'ji-gallaorol',  'G''allaorol',      'Галляаральский', 'Gallaorol'),
  ('jizzakh', 'ji-mirzachol',  'Mirzacho''l',      'Мирзачульский',  'Mirzachol'),
  ('jizzakh', 'ji-paxtakor',   'Paxtakor',         'Пахтакорский',   'Paxtakor'),
  ('jizzakh', 'ji-rashidov',   'Sharof Rashidov',  'Шараф-Рашидовский','Sharof Rashidov'),
  ('jizzakh', 'ji-yangiobod',  'Yangiobod',        'Янгиабадский',   'Yangiobod'),
  ('jizzakh', 'ji-zafarobod',  'Zafarobod',        'Зафарабадский',  'Zafarobod'),
  ('jizzakh', 'ji-zarbdor',    'Zarbdor',          'Зарбдарский',    'Zarbdor'),
  ('jizzakh', 'ji-jizzax-c',   'Jizzax shahri',    'город Джизак',   'Jizzakh City'),
  -- Namangan -----------------------------------------------------------------
  ('namangan', 'na-chortoq',     'Chortoq',        'Чартакский',     'Chortoq'),
  ('namangan', 'na-chust',       'Chust',          'Чустский',       'Chust'),
  ('namangan', 'na-kosonsoy',    'Kosonsoy',       'Касансайский',   'Kosonsoy'),
  ('namangan', 'na-mingbuloq',   'Mingbuloq',      'Мингбулакский',  'Mingbuloq'),
  ('namangan', 'na-namangan',    'Namangan tumani','Наманганский',   'Namangan District'),
  ('namangan', 'na-norin',       'Norin',          'Нарынский',      'Norin'),
  ('namangan', 'na-pop',         'Pop',            'Папский',        'Pop'),
  ('namangan', 'na-toraqorgon',  'To''raqo''rg''on','Туракурганский','Toraqorgon'),
  ('namangan', 'na-uchqorgon',   'Uchqo''rg''on',  'Учкурганский',   'Uchqorgon'),
  ('namangan', 'na-uychi',       'Uychi',          'Уйчинский',      'Uychi'),
  ('namangan', 'na-yangiqorgon', 'Yangiqo''rg''on','Янгикурганский', 'Yangiqorgon'),
  ('namangan', 'na-namangan-c',  'Namangan shahri','город Наманган', 'Namangan City'),
  -- Navoiy -------------------------------------------------------------------
  ('navoiy', 'nv-karmana',   'Karmana',          'Карманинский',   'Karmana'),
  ('navoiy', 'nv-konimex',   'Konimex',          'Канимехский',    'Konimex'),
  ('navoiy', 'nv-navbahor',  'Navbahor',         'Навбахорский',   'Navbahor'),
  ('navoiy', 'nv-nurota',    'Nurota',           'Нуратинский',    'Nurota'),
  ('navoiy', 'nv-qiziltepa', 'Qiziltepa',        'Кызылтепинский', 'Qiziltepa'),
  ('navoiy', 'nv-tomdi',     'Tomdi',            'Тамдынский',     'Tomdi'),
  ('navoiy', 'nv-uchquduq',  'Uchquduq',         'Учкудукский',    'Uchquduq'),
  ('navoiy', 'nv-xatirchi',  'Xatirchi',         'Хатырчинский',   'Xatirchi'),
  ('navoiy', 'nv-navoiy-c',  'Navoiy shahri',    'город Навои',    'Navoiy City'),
  ('navoiy', 'nv-zarafshon', 'Zarafshon shahri', 'город Зарафшан', 'Zarafshan City'),
  -- Kashkadarya --------------------------------------------------------------
  ('kashkadarya', 'qa-chiroqchi',    'Chiroqchi',      'Чиракчинский',   'Chiroqchi'),
  ('kashkadarya', 'qa-dehqonobod',   'Dehqonobod',     'Дехканабадский', 'Dehqonobod'),
  ('kashkadarya', 'qa-guzor',        'G''uzor',        'Гузарский',      'Guzor'),
  ('kashkadarya', 'qa-kasbi',        'Kasbi',          'Касбийский',     'Kasbi'),
  ('kashkadarya', 'qa-kitob',        'Kitob',          'Китабский',      'Kitob'),
  ('kashkadarya', 'qa-koson',        'Koson',          'Касанский',      'Koson'),
  ('kashkadarya', 'qa-mirishkor',    'Mirishkor',      'Миришкорский',   'Mirishkor'),
  ('kashkadarya', 'qa-muborak',      'Muborak',        'Мубарекский',    'Muborak'),
  ('kashkadarya', 'qa-nishon',       'Nishon',         'Нишанский',      'Nishon'),
  ('kashkadarya', 'qa-qamashi',      'Qamashi',        'Камашинский',    'Qamashi'),
  ('kashkadarya', 'qa-qarshi',       'Qarshi tumani',  'Каршинский',     'Qarshi District'),
  ('kashkadarya', 'qa-shahrisabz',   'Shahrisabz tumani','Шахрисабзский','Shahrisabz District'),
  ('kashkadarya', 'qa-yakkabog',     'Yakkabog''',     'Яккабагский',    'Yakkabog'),
  ('kashkadarya', 'qa-qarshi-c',     'Qarshi shahri',  'город Карши',    'Qarshi City'),
  ('kashkadarya', 'qa-shahrisabz-c', 'Shahrisabz shahri','город Шахрисабз','Shahrisabz City'),
  -- Samarkand ----------------------------------------------------------------
  ('samarkand', 'sa-bulungur',     'Bulung''ur',       'Булунгурский',   'Bulungur'),
  ('samarkand', 'sa-ishtixon',     'Ishtixon',         'Иштыханский',    'Ishtixon'),
  ('samarkand', 'sa-jomboy',       'Jomboy',           'Джамбайский',    'Jomboy'),
  ('samarkand', 'sa-kattaqorgon',  'Kattaqo''rg''on tumani','Каттакурганский','Kattaqorgon District'),
  ('samarkand', 'sa-narpay',       'Narpay',           'Нарпайский',     'Narpay'),
  ('samarkand', 'sa-nurobod',      'Nurobod',          'Нурабадский',    'Nurobod'),
  ('samarkand', 'sa-oqdaryo',      'Oqdaryo',          'Акдарьинский',   'Oqdaryo'),
  ('samarkand', 'sa-pastdargom',   'Pastdarg''om',     'Пастдаргомский', 'Pastdargom'),
  ('samarkand', 'sa-paxtachi',     'Paxtachi',         'Пахтачийский',   'Paxtachi'),
  ('samarkand', 'sa-payariq',      'Payariq',          'Пайарыкский',    'Payariq'),
  ('samarkand', 'sa-qoshrabot',    'Qo''shrabot',      'Кушрабадский',   'Qoshrabot'),
  ('samarkand', 'sa-samarqand',    'Samarqand tumani', 'Самаркандский',  'Samarkand District'),
  ('samarkand', 'sa-toyloq',       'Toyloq',           'Тайлакский',     'Toyloq'),
  ('samarkand', 'sa-urgut',        'Urgut',            'Ургутский',      'Urgut'),
  ('samarkand', 'sa-samarqand-c',  'Samarqand shahri', 'город Самарканд','Samarkand City'),
  ('samarkand', 'sa-kattaqorgon-c','Kattaqo''rg''on shahri','город Каттакурган','Kattaqorgon City'),
  -- Sirdaryo -----------------------------------------------------------------
  ('sirdaryo', 'si-boyovut',    'Boyovut',          'Баяутский',      'Boyovut'),
  ('sirdaryo', 'si-guliston',   'Guliston tumani',  'Гулистанский',   'Guliston District'),
  ('sirdaryo', 'si-mirzaobod',  'Mirzaobod',        'Мирзаабадский',  'Mirzaobod'),
  ('sirdaryo', 'si-oqoltin',    'Oqoltin',          'Акалтынский',    'Oqoltin'),
  ('sirdaryo', 'si-sardoba',    'Sardoba',          'Сардобинский',   'Sardoba'),
  ('sirdaryo', 'si-sayxunobod', 'Sayxunobod',       'Сайхунабадский', 'Sayxunobod'),
  ('sirdaryo', 'si-sirdaryo',   'Sirdaryo tumani',  'Сырдарьинский',  'Sirdaryo District'),
  ('sirdaryo', 'si-xovos',      'Xovos',            'Хавастский',     'Xovos'),
  ('sirdaryo', 'si-guliston-c', 'Guliston shahri',  'город Гулистан', 'Guliston City'),
  ('sirdaryo', 'si-shirin',     'Shirin shahri',    'город Ширин',    'Shirin City'),
  ('sirdaryo', 'si-yangiyer',   'Yangiyer shahri',  'город Янгиер',   'Yangiyer City'),
  -- Surkhandarya -------------------------------------------------------------
  ('surkhandarya', 'su-angor',      'Angor',        'Ангорский',      'Angor'),
  ('surkhandarya', 'su-bandixon',   'Bandixon',     'Бандиханский',   'Bandixon'),
  ('surkhandarya', 'su-boysun',     'Boysun',       'Байсунский',     'Boysun'),
  ('surkhandarya', 'su-denov',      'Denov',        'Денауский',      'Denov'),
  ('surkhandarya', 'su-jarqorgon',  'Jarqo''rg''on','Джаркурганский', 'Jarqorgon'),
  ('surkhandarya', 'su-muzrabot',   'Muzrabot',     'Музрабадский',   'Muzrabot'),
  ('surkhandarya', 'su-oltinsoy',   'Oltinsoy',     'Алтынсайский',   'Oltinsoy'),
  ('surkhandarya', 'su-qiziriq',    'Qiziriq',      'Кизирикский',    'Qiziriq'),
  ('surkhandarya', 'su-qumqorgon',  'Qumqo''rg''on','Кумкурганский',  'Qumqorgon'),
  ('surkhandarya', 'su-sariosiyo',  'Sariosiyo',    'Сариасийский',   'Sariosiyo'),
  ('surkhandarya', 'su-sherobod',   'Sherobod',     'Шерабадский',    'Sherobod'),
  ('surkhandarya', 'su-shorchi',    'Sho''rchi',    'Шурчинский',     'Shorchi'),
  ('surkhandarya', 'su-termiz',     'Termiz tumani','Термезский',     'Termez District'),
  ('surkhandarya', 'su-uzun',       'Uzun',         'Узунский',       'Uzun'),
  ('surkhandarya', 'su-termiz-c',   'Termiz shahri','город Термез',   'Termez City'),
  -- Khorezm ------------------------------------------------------------------
  ('khorezm', 'xo-bogot',      'Bog''ot',         'Багатский',      'Bogot'),
  ('khorezm', 'xo-gurlan',     'Gurlan',          'Гурленский',     'Gurlan'),
  ('khorezm', 'xo-hazorasp',   'Hazorasp',        'Хазараспский',   'Hazorasp'),
  ('khorezm', 'xo-xiva',       'Xiva tumani',     'Хивинский',      'Khiva District'),
  ('khorezm', 'xo-qoshkopir',  'Qo''shko''pir',   'Кошкупырский',   'Qoshkopir'),
  ('khorezm', 'xo-shovot',     'Shovot',          'Шаватский',      'Shovot'),
  ('khorezm', 'xo-urganch',    'Urganch tumani',  'Ургенчский',     'Urgench District'),
  ('khorezm', 'xo-xonqa',      'Xonqa',           'Ханкинский',     'Xonqa'),
  ('khorezm', 'xo-yangiariq',  'Yangiariq',       'Янгиарыкский',   'Yangiariq'),
  ('khorezm', 'xo-yangibozor', 'Yangibozor',      'Янгибазарский',  'Yangibozor'),
  ('khorezm', 'xo-tuproqqala', 'Tuproqqal''a',    'Тупраккалинский','Tuproqqala'),
  ('khorezm', 'xo-urganch-c',  'Urganch shahri',  'город Ургенч',   'Urgench City'),
  ('khorezm', 'xo-xiva-c',     'Xiva shahri',     'город Хива',     'Khiva City'),
  -- Karakalpakstan -----------------------------------------------------------
  ('karakalpakstan', 'qq-amudaryo',   'Amudaryo',       'Амударьинский',  'Amudaryo'),
  ('karakalpakstan', 'qq-beruniy',    'Beruniy',        'Берунийский',    'Beruniy'),
  ('karakalpakstan', 'qq-chimboy',    'Chimboy',        'Чимбайский',     'Chimboy'),
  ('karakalpakstan', 'qq-ellikqala',  'Ellikqal''a',    'Элликкалинский', 'Ellikqala'),
  ('karakalpakstan', 'qq-kegeyli',    'Kegeyli',        'Кегейлийский',   'Kegeyli'),
  ('karakalpakstan', 'qq-moynoq',     'Mo''ynoq',       'Муйнакский',     'Moynoq'),
  ('karakalpakstan', 'qq-nukus',      'Nukus tumani',   'Нукусский',      'Nukus District'),
  ('karakalpakstan', 'qq-qanlikol',   'Qanliko''l',     'Канлыкульский',  'Qanlikol'),
  ('karakalpakstan', 'qq-qoraozak',   'Qorao''zak',     'Караузякский',   'Qoraozak'),
  ('karakalpakstan', 'qq-qongirot',   'Qo''ng''irot',   'Кунградский',    'Qongirot'),
  ('karakalpakstan', 'qq-shumanay',   'Shumanay',       'Шуманайский',    'Shumanay'),
  ('karakalpakstan', 'qq-taxtakopir', 'Taxtako''pir',   'Тахтакупырский', 'Taxtakopir'),
  ('karakalpakstan', 'qq-tortkol',    'To''rtko''l',    'Турткульский',   'Tortkol'),
  ('karakalpakstan', 'qq-xojayli',    'Xo''jayli',      'Ходжейлийский',  'Xojayli'),
  ('karakalpakstan', 'qq-nukus-c',    'Nukus shahri',   'город Нукус',    'Nukus City')
)
insert into public.districts (region_id, code, name_uz, name_ru, name_en, sort_order)
select r.id, d.code, d.name_uz, d.name_ru, d.name_en, row_number() over (partition by d.region_code order by d.name_uz)
from data d
join public.regions r on r.code = d.region_code
on conflict (code) do update
  set name_uz = excluded.name_uz,
      name_ru = excluded.name_ru,
      name_en = excluded.name_en;

-- -----------------------------------------------------------------------------
-- Voice types
-- -----------------------------------------------------------------------------
insert into public.voice_types (code, name_uz, name_ru, name_en, sort_order) values
  ('soprano',       'Soprano',           'Сопрано',          'Soprano',        1),
  ('mezzo-soprano', 'Mecco-soprano',     'Меццо-сопрано',    'Mezzo-soprano',  2),
  ('contralto',     'Kontralto',         'Контральто',       'Contralto',      3),
  ('countertenor',  'Kontrtenor',        'Контратенор',      'Countertenor',   4),
  ('tenor',         'Tenor',             'Тенор',            'Tenor',          5),
  ('baritone',      'Bariton',           'Баритон',          'Baritone',       6),
  ('bass',          'Bas',               'Бас',              'Bass',           7),
  ('other',         'Boshqa',            'Другой',           'Other',          8)
on conflict (code) do update
  set name_uz = excluded.name_uz, name_ru = excluded.name_ru, name_en = excluded.name_en;

-- -----------------------------------------------------------------------------
-- Age categories
-- -----------------------------------------------------------------------------
-- § IV of the Regulations. `min_age` for «Романс без границ» is the competition's
-- youngest admissible age rather than a rule of its own — the document sets only a
-- ceiling, and the CHECK constraint needs a floor. See 0011.
insert into public.age_categories
  (code, name_uz, name_ru, name_en, min_age, max_age, sort_order) values
  ('hope',       'Romansiada umidi',  'Надежда Романсиады',  'Hope of Romansiada',      12, 17, 1),
  ('young',      'Yosh ijrochilar',   'Молодые исполнители', 'Young performers',        18, 27, 2),
  ('no-borders', 'Chegarasiz romans', 'Романс без границ',   'Romance without borders', 12, 35, 3)
on conflict (code) do update
  set name_uz = excluded.name_uz,
      name_ru = excluded.name_ru,
      name_en = excluded.name_en,
      min_age = excluded.min_age,
      max_age = excluded.max_age,
      sort_order = excluded.sort_order;

-- -----------------------------------------------------------------------------
-- Nominations
-- -----------------------------------------------------------------------------
-- «Номинация» on the official application form. § IV of the Regulations defines
-- exactly two creative directions, and this list must not offer a third: an entry
-- filed under a category the jury does not judge cannot be scored. See 0011.
insert into public.nominations (code, name_uz, name_ru, name_en, sort_order) values
  ('russian-romance', 'Rus romansi',     'Русский романс',   'Russian romance', 1),
  ('uzbek-romance',   'O''zbek romansi', 'Узбекский романс', 'Uzbek romance',   2)
on conflict (code) do update
  set name_uz = excluded.name_uz,
      name_ru = excluded.name_ru,
      name_en = excluded.name_en,
      sort_order = excluded.sort_order;

-- -----------------------------------------------------------------------------
-- News categories
-- -----------------------------------------------------------------------------
insert into public.news_categories (slug, sort_order) values
  ('announcements', 1), ('festival', 2), ('interviews', 3), ('results', 4), ('press', 5)
on conflict (slug) do nothing;

with data (slug, locale, name) as (values
  ('announcements', 'uz', 'E''lonlar'),      ('announcements', 'ru', 'Анонсы'),      ('announcements', 'en', 'Announcements'),
  ('festival',      'uz', 'Festival'),       ('festival',      'ru', 'Фестиваль'),   ('festival',      'en', 'Festival'),
  ('interviews',    'uz', 'Intervyular'),    ('interviews',    'ru', 'Интервью'),    ('interviews',    'en', 'Interviews'),
  ('results',       'uz', 'Natijalar'),      ('results',       'ru', 'Результаты'),  ('results',       'en', 'Results'),
  ('press',         'uz', 'Matbuot'),        ('press',         'ru', 'Пресса'),      ('press',         'en', 'Press')
)
insert into public.news_category_translations (category_id, locale, name)
select c.id, d.locale::public.locale_code, d.name
from data d join public.news_categories c on c.slug = d.slug
on conflict (category_id, locale) do update set name = excluded.name;

-- -----------------------------------------------------------------------------
-- Video categories
-- -----------------------------------------------------------------------------
insert into public.video_categories (slug, sort_order) values
  ('performances', 1), ('interviews', 2), ('reports', 3), ('masterclasses', 4)
on conflict (slug) do nothing;

with data (slug, locale, name) as (values
  ('performances',  'uz', 'Chiqishlar'),      ('performances',  'ru', 'Выступления'),   ('performances',  'en', 'Performances'),
  ('interviews',    'uz', 'Intervyular'),     ('interviews',    'ru', 'Интервью'),      ('interviews',    'en', 'Interviews'),
  ('reports',       'uz', 'Reportajlar'),     ('reports',       'ru', 'Репортажи'),     ('reports',       'en', 'Reports'),
  ('masterclasses', 'uz', 'Mahorat darslari'),('masterclasses', 'ru', 'Мастер-классы'), ('masterclasses', 'en', 'Masterclasses')
)
insert into public.video_category_translations (category_id, locale, name)
select c.id, d.locale::public.locale_code, d.name
from data d join public.video_categories c on c.slug = d.slug
on conflict (category_id, locale) do update set name = excluded.name;

-- -----------------------------------------------------------------------------
-- Site settings defaults
-- -----------------------------------------------------------------------------
update public.site_settings set
  branding = jsonb_build_object(
    'logoPath', null,
    'faviconPath', null,
    'primaryColor', '#7A1220',
    'accentColor', '#C9A227'
  ),
  contacts = jsonb_build_object(
    'phone', '+998 71 200 00 00',
    'email', 'info@romansiada.uz',
    'addressUz', 'Toshkent shahri, Amir Temur shoh ko''chasi 1',
    'addressRu', 'город Ташкент, проспект Амира Темура, 1',
    'addressEn', '1 Amir Temur Avenue, Tashkent',
    'workingHours', '09:00 – 18:00',
    'mapLat', 41.311081,
    'mapLng', 69.279737
  ),
  social = jsonb_build_object(
    'telegram', 'https://t.me/romansiada_uz',
    'instagram', 'https://instagram.com/romansiada.uz',
    'facebook', 'https://facebook.com/romansiada.uz',
    'youtube', 'https://youtube.com/@romansiada'
  ),
  stats = jsonb_build_object(
    'years', 20, 'participants', 1000, 'countries', 20, 'goal', 1
  ),
  seo = jsonb_build_object('defaultOgImage', null, 'verificationGoogle', null),
  analytics = jsonb_build_object('googleAnalyticsId', null, 'yandexMetrikaId', null)
where id = 1;
