-- =============================================================================
-- 0004 — Festival applications
-- =============================================================================
-- Mirrors the official paper form, «Заявка на участие в Международном конкурсе
-- молодых исполнителей русского и узбекского романса "Узбекская Романсиада"»,
-- field for field. The organisers' decision is that the online form asks for
-- exactly what the blank asks for and nothing more.
--
-- That decision is also the strongest privacy control in the product. Earlier
-- drafts of this table carried passport numbers, passport scans, portraits and
-- performance videos of applicants who are frequently minors. None of that is
-- on the paper form, so none of it is collected: the columns are gone, the
-- private `applications` bucket is gone with them (see 0008), and the residual
-- exposure of this table is now a name, a date of birth and contact details.
--
-- SECURITY POSTURE — there is deliberately NO `anon` INSERT policy on this
-- table (see 0007_rls.sql). Public submissions travel through a Server Action
-- that validates with Zod, enforces a rate limit, then writes using the
-- service-role client. Consequence: an attacker holding the publishable
-- anon key can neither read nor write applications.
-- =============================================================================

create table if not exists public.registrations (
  id                uuid primary key default gen_random_uuid(),

  -- Human-quotable identifier, e.g. RMS-2026-004821. Generated by trigger below.
  reference_code    text not null unique,

  -- «ФИО конкурсанта» --------------------------------------------------------
  first_name        text not null,
  last_name         text not null,
  middle_name       text,

  -- «Возраст» / «Дата рождения» ----------------------------------------------
  -- Age is not stored. It is a function of the birth date and today, and a
  -- stored copy is wrong the day after it is written.
  birth_date        date not null,

  -- «Название учебного заведения, факультет, место работы (учебы), должность» -
  institution       text,
  faculty           text,
  position_title    text,

  -- «Место жительства» / «E-mail» / «Телефон» --------------------------------
  address           text not null,
  email             citext not null,
  phone             text not null,

  -- «Программа»: I тур / II тур / III тур ------------------------------------
  -- Three columns rather than one repertoire blob, because the form asks for
  -- three and the jury reads them one round at a time. Free text: entries are
  -- "composer — title" lines, one per piece.
  programme_round_1 text,
  programme_round_2 text,
  programme_round_3 text,

  -- «ФИО концертмейстера, место работы» --------------------------------------
  -- The accompanist, not the applicant's teacher. Optional: a competitor may
  -- perform to a backing track or bring no pianist to the first round.
  accompanist_name       text,
  accompanist_workplace  text,

  -- «Номинация» ---------------------------------------------------------------
  nomination_id     uuid references public.nominations (id) on delete restrict,

  -- Review workflow ----------------------------------------------------------
  status            public.registration_status not null default 'pending',
  review_note       text,
  reviewed_by       uuid references public.profiles (id) on delete set null,
  reviewed_at       timestamptz,

  -- Audit / anti-abuse -------------------------------------------------------
  consent_given_at  timestamptz not null default now(),
  submitted_ip      inet,
  user_agent        text,
  locale            public.locale_code not null default 'uz',

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint registrations_birth_date_sane
    check (birth_date > date '1900-01-01' and birth_date < current_date),

  -- A decided application must say who decided it and when.
  constraint registrations_review_complete
    check (status = 'pending' or (reviewed_at is not null))
);

comment on table public.registrations is
  'Festival applications, matching the official paper form field for field.
   Still personal data under Uzbek law No. ZRU-547 — names, dates of birth and
   contact details — but deliberately holds no identity documents.';

comment on column public.registrations.position_title is
  'Должность. Named `position_title` because `position` is a reserved word in
   SQL and would need quoting at every call site.';

drop trigger if exists registrations_set_updated_at on public.registrations;
create trigger registrations_set_updated_at
  before update on public.registrations
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Reference code generation
-- -----------------------------------------------------------------------------
-- A per-year sequence keeps codes short and human-readable. Generating it in the
-- database rather than the application removes the read-then-write race that a
-- "SELECT max(...) + 1" in Node would otherwise have under concurrent submissions.
create sequence if not exists public.registration_reference_seq;

create or replace function public.assign_registration_reference()
returns trigger
language plpgsql
as $$
begin
  if new.reference_code is null or new.reference_code = '' then
    new.reference_code := format(
      'RMS-%s-%s',
      to_char(now(), 'YYYY'),
      lpad(nextval('public.registration_reference_seq')::text, 6, '0')
    );
  end if;
  return new;
end;
$$;

drop trigger if exists registrations_assign_reference on public.registrations;
create trigger registrations_assign_reference
  before insert on public.registrations
  for each row execute function public.assign_registration_reference();

-- -----------------------------------------------------------------------------
-- Review stamping
-- -----------------------------------------------------------------------------
-- Keeps `reviewed_at` truthful even if an action forgets to set it, and clears
-- the stamp if an application is moved back to `pending`.
create or replace function public.stamp_registration_review()
returns trigger
language plpgsql
as $$
begin
  if new.status is distinct from old.status then
    if new.status = 'pending' then
      new.reviewed_at := null;
      new.reviewed_by := null;
    else
      new.reviewed_at := coalesce(new.reviewed_at, now());
      new.reviewed_by := coalesce(new.reviewed_by, auth.uid());
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists registrations_stamp_review on public.registrations;
create trigger registrations_stamp_review
  before update on public.registrations
  for each row execute function public.stamp_registration_review();

-- -----------------------------------------------------------------------------
-- Duplicate protection
-- -----------------------------------------------------------------------------
-- Partial unique indexes rather than table constraints: a rejected applicant
-- should be able to re-apply next season, so only live applications collide.
create unique index if not exists registrations_unique_active_email
  on public.registrations (email)
  where status <> 'rejected';

-- E-mail is now the only duplicate check. The passport-number index that used to
-- sit here went with the column: the form does not ask for a passport, so the
-- system has no second identifier to deduplicate on. Two applications from the
-- same person under two addresses are therefore possible, and are left for a
-- reviewer to spot — which is the same position the paper process was in.
